# Generated by Django 3.0.7 on 2020-06-22 21:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0007_auto_20200621_1602'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicant',
            name='applied_at',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='applicant',
            name='job',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='job.Job'),
        ),
    ]
